### ISSUE TITLE
Problem with nodes of multi-part lines

### ISSUE THREAD

**Issue by saberraz** [wonder-sk/CadNodeTool#20] opened 2016-08-29 11:07 UTC
Steps to reproduce
1. Add a part to a line
2. Try to move the node using the CAD node tool 
3. Crash

```
Traceback (most recent call last):
  File "C:/Users/saber/.qgis2/python/plugins\CadNodeTool\nodetool.py", line 272, in cadCanvasMoveEvent
    self.mouse_move_not_dragging(e)
  File "C:/Users/saber/.qgis2/python/plugins\CadNodeTool\nodetool.py", line 412, in mouse_move_not_dragging
    if self.is_match_at_endpoint(m):
  File "C:/Users/saber/.qgis2/python/plugins\CadNodeTool\nodetool.py", line 359, in is_match_at_endpoint
    polyline = _geometry_to_polyline(geom)  # TODO: does not work with multi-type
  File "C:/Users/saber/.qgis2/python/plugins\CadNodeTool\nodetool.py", line 75, in _geometry_to_polyline
    assert isinstance(g, QgsCurveV2)
AssertionError

```

CadNodeTool 1.0, QGIS 2.14.5-Essen on Windows 7

**Comment by wonder-sk** [comment] 2016-11-09 03:38
Duplicate of #18

**Closed as completed by wonder-sk** 2016-11-09 03:38 UTC
